### ISSUE TITLE
Create basic bolt.yaml

### ISSUE THREAD

**Issue by cloudoops** [cloudoops/better-logs#3]

**Comment by jelockro** [comment]
I can do this

**Comment by jelockro** [comment]
I am trying to create a pull request, but apparently I can't since my previous request has not been processed for the Write-Content Issue

**Comment by cloudoops** [comment]
Okay, thank you for your previous pull request, it has been merged.

**Comment by cloudoops** [comment]
I guess we merged this content along with your other commit when we merged the code.
